# Generated by Django 5.0.7 on 2024-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weathermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('City', models.CharField(max_length=66)),
                ('Rain', models.CharField(max_length=5)),
                ('Temperature', models.CharField(max_length=5)),
            ],
        ),
    ]
