# Generated by Django 5.0.7 on 2024-08-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_registermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
