# Generated by Django 5.0.7 on 2024-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_delete_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=35, unique=True)),
                ('Password', models.CharField(max_length=35)),
                ('City', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
